# Generated by Django 6.0.3 on 2026-03-27 20:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QRCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "character",
                    models.CharField(max_length=100, verbose_name="Персонаж"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Кампания",
                "verbose_name_plural": "QR Кампании",
            },
        ),
        migrations.CreateModel(
            name="QRCodeLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("scans", models.IntegerField(default=0, verbose_name="Сканирований")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_codes",
                        to="quests.qrcampaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Код",
                "verbose_name_plural": "QR Коды",
                "indexes": [
                    models.Index(fields=["code"], name="quests_qrco_code_d6d79a_idx"),
                    models.Index(
                        fields=["campaign", "created_at"],
                        name="quests_qrco_campaig_6717ac_idx",
                    ),
                ],
            },
        ),
    ]
