# Generated by Django 6.0.3 on 2026-03-28 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointOfInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Краткое описание")),
                (
                    "info",
                    models.TextField(blank=True, verbose_name="Подробная информация"),
                ),
                ("coords_lat", models.FloatField(verbose_name="Широта")),
                ("coords_lng", models.FloatField(verbose_name="Долгота")),
                (
                    "points",
                    models.IntegerField(default=0, verbose_name="Баллы за посещение"),
                ),
                (
                    "qr_points",
                    models.IntegerField(default=0, verbose_name="Баллы за QR"),
                ),
                (
                    "radius",
                    models.IntegerField(
                        default=100, verbose_name="Радиус подтверждения (м)"
                    ),
                ),
                ("image", models.URLField(blank=True, verbose_name="URL изображения")),
                (
                    "character_name",
                    models.CharField(max_length=100, verbose_name="Имя персонажа"),
                ),
                ("character_text", models.TextField(verbose_name="Текст персонажа")),
                (
                    "character_voice_rate",
                    models.FloatField(default=1.0, verbose_name="Скорость речи"),
                ),
                (
                    "character_voice_pitch",
                    models.FloatField(default=1.0, verbose_name="Высота тона"),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Активна в игре"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Точка интереса",
                "verbose_name_plural": "Точки интереса",
            },
        ),
        migrations.CreateModel(
            name="POIQRCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("scans", models.IntegerField(default=0, verbose_name="Сканирований")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "QR-код POI",
                "verbose_name_plural": "QR-коды POI",
            },
        ),
        migrations.RemoveIndex(
            model_name="qrcodelink",
            name="quests_qrco_code_d6d79a_idx",
        ),
        migrations.RemoveIndex(
            model_name="qrcodelink",
            name="quests_qrco_campaig_6717ac_idx",
        ),
        migrations.AddField(
            model_name="poiqrcode",
            name="poi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qr_codes",
                to="quests.pointofinterest",
            ),
        ),
        migrations.RemoveField(
            model_name="qrcodelink",
            name="campaign",
        ),
        migrations.AddIndex(
            model_name="poiqrcode",
            index=models.Index(fields=["code"], name="quests_poiq_code_a3083e_idx"),
        ),
        migrations.AddIndex(
            model_name="poiqrcode",
            index=models.Index(
                fields=["poi", "created_at"], name="quests_poiq_poi_id_63dd2e_idx"
            ),
        ),
        migrations.DeleteModel(
            name="QRCampaign",
        ),
        migrations.DeleteModel(
            name="QRCodeLink",
        ),
    ]
